all:
  children:
    routers:
      hosts:
        vm-router:
          ansible_host: 192.168.1.186
          ansible_user: silak
    webservers:
      hosts:
        vm-web:
          ansible_host: 192.168.20.10
          ansible_user: silak
    databases:
      hosts:
        vm-db:
          ansible_host: 192.168.30.10
          ansible_user: silak
    monitoring:
      hosts:
        vm-monitoring:
          ansible_host: 192.168.40.10
          ansible_user: silak
    ai:
      hosts:
        vm-ai:
          ansible_host: 192.168.50.10
          ansible_user: silak
    soc:
      hosts:
        vm-soc:
          ansible_host: 192.168.70.10
          ansible_user: silak
    payroll:
      hosts:
        vm-payroll:
          ansible_host: 192.168.60.10
          ansible_user: silak
